# app/config/security.yml
# Installation FosUser: http://symfony.com/doc/current/bundles/FOSUserBundle/index.html
# tuto FosUser : https://www.idci-consulting.fr/fr/article/fos-user-bundle
security:
    encoders:
        CoreBundle\Entity\Users: sha512

    role_hierarchy:
        ROLE_MODERATOR:    ROLE_USER
        ROLE_OPERATOR:    [ROLE_USER, ROLE_MODERATOR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_OPERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:    ^/(connexion|enregistrement|validation|reinitialisation|confirmation|login_failure)
            anonymous: true
        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                failure_path: login_failure
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_MODERATOR }